### ISSUE TITLE
FormsCustomControls not updating

### ISSUE THREAD

**Issue by JoshuaNovak919** [tvand7093/Xamarin-Samples#1]
I have a project built in a similar manner as your FormsCustomControls sample, but I passed the binding context to a new page when you click on a list item. For some reason on that new page, the binding I pass into my FormsCustomControls does not show up and it never calls the property changing method. Any ideas?

**Comment by tvand7093** [comment]
so it sounds like the control isn't binding correctly. It's hard to say really without any code to look at. Have you seen my accompanying blog post? http://xamandor.me/2015/02/27/custom-controls-with-xamarin-forms/ 

On distinct thing to recognize is the setting of the binding mode to two way. That's important to let the view know when something has changed. That would be a starting place to look.

**Comment by JoshuaNovak919** [comment]
Yeah I followed that tutorial as I was looking at the samples. I'll build a very basic sample project in the morning and see if I can solve the issue. If i'm still having the same issue i'll post a link to the project.

**Comment by JoshuaNovak919** [comment]
It was a mess up on my end. I added `this.BindingContext = this;` to the Custom control so I could use binding in the template for default values. How can you use the default values correctly? Basically I want elements to have `IsVisible` set to false by default, but if a title is set then `IsVisible` should be set to true. The user does not call the element directly and does not have to set a title, which makes it so the property never gets called.

**Comment by tvand7093** [comment]
The way I would do that is if this control is always following that rule, just set the the IsVisible properties on your controls when your custom control gets created. So using my example, you could do something like: 

```
public CustomHeaderBox ()
{
    InitializeComponent ();
        mySubControl.IsVisible = false;
}
```

This should force it to set IsVisible to false on start, and if there is a change in the title, you would trigger the change of IsVisible yourself in that handler. This is what I would start with.

**Comment by JoshuaNovak919** [comment]
Thanks for all your help!! I ended up making a `TitleIsVisible` bindable property and then I did this:

```
public CustomHeaderBox ()
{
    InitializeComponent ();
    myTitle.IsVisible = TitleIsVisible;
}
```

This let me set a default value in the BindableProperty and I can allow the `TitleIsVisible` property to be passed too, making it an optional property.
